# Generated by Django 5.0.2 on 2024-02-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazingspiderman',
            fields=[
                ('comicid', models.AutoField(db_column='comicId', primary_key=True, serialize=False)),
                ('seriesid', models.CharField(blank=True, db_column='seriesId', max_length=45, null=True)),
                ('issueid', models.CharField(blank=True, db_column='issueId', max_length=45, null=True)),
                ('issuenumber', models.CharField(blank=True, db_column='issueNumber', max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('img_path', models.TextField(blank=True, null=True)),
                ('img_extension', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'amazingspiderman',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
